### ISSUE TITLE
Tourist

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/PHS#11]
![screenshot0](https://user-images.githubusercontent.com/12796450/37033654-c031b852-2157-11e8-9661-507a97d547b3.png)

and "tourist" hire a random trait (Pilot, Engineer, Scientist)

**Comment by linuxgurugamer** [comment]
What?  You don't want to hire a tourist?  

I wonder why not ?   :-)

Probably there because of the localization changes I did, I'll get it fixed
Thanks

**Comment by yalov** [comment]
Actually "random" trait button is a good idea. (with non-random trait cost modifier)
