### ISSUE TITLE
fire event at kerbal generation

### ISSUE THREAD

**Issue by Sigma88** [linuxgurugamer/PHS#15]
stock ksp usually fires an event when a new kerbal is generated.

if I am reading the code correctly this is where you end the generation of your new kerbal:

https://github.com/linuxgurugamer/PHS/blob/afbf5d2fe8ba2aa81d0b7fd889de1703e6c23634/Hire/CustomAstronautComplexUI.cs#L176

would it be possible for you to fire the stock event so that other mods can be aware of the newly generated kerbal?

the event is one of these two, I'm not sure which one would work best since one of them is new and I haven't looked at how it behaves yet.

```
GameEvents.onKerbalAdded // old gameevent most likely to be used by other mods
GameEvents.onKerbalAddComplete // new gameevent that seems relevant
```

edit: since this feature is mostly to facilitate interactions between mods, I am available to do testing with one of my mods that might use that event so that we can find the best solution that would improve compatibility for everyone

**Comment by linuxgurugamer** [comment]
That's not too difficult, I'll see if I can do something this evening

**Comment by linuxgurugamer** [comment]
Here you go:
For 1.5.1:  https://jenkins.spacetux.net/job/T-Z/job/TRP-Hire/89/artifact/TRP-Hire-0.6.8.8.zip
For 1.4.5:  https://jenkins.spacetux.net/job/T-Z/job/TRP-Hire/89/artifact/TRP-Hire-1.4.5-0.6.8.8.zip

Let me know if there are any issues, I added both methods at the end of the loop, at line: 176, before the brace

**Comment by Sigma88** [comment]
I saw you added the events (thanks by the way)

I tested them but I don't get the result I am expecting. I will need to look a bit more into this and I will let you know

**Comment by Sigma88** [comment]
nevermind, it works great, I just didn't notice that my mod only changes the stats of Applicants and you are generating directly crewmembers,

I was worried that my mod could mess up the TRP generation but since you don't generate applicants it won't 🎉

**Comment by linuxgurugamer** [comment]
Good to know.  I'll probably do a release in a day or so
