### ISSUE TITLE
static KLevel carries between saves

### ISSUE THREAD

**Issue by cake-pie** [linuxgurugamer/PHS#22]
- Start KSP
- Create new career game, under advanced tab in difficulty options turn off "Enable Kerbal Experience", call this "Game A"
- Go to astronaut complex, note cost to hire is 25k (because internally `KLevel = 0`)
  - because `kerExp` is false, this is cost to hire a max level kerbal
- Exit to main menu
- Create new career game, ensure difficulty options set to Normal with "Enable Kerbal Experience" on, call this "Game B"
- Use Alt-F12 cheat menu to grant max facility upgrades
- Go to astronaut complex, select Level 2, note cost to hire is 75k (internally `KLevel = 2`)
  - no need to actually perform the hire
- Exit to main menu
- Load Game A again.
- Go to astronaut complex, note cost to hire is 75k (because `KLevel = 2` from Game B)
  - again, this is the cost to hire a max level kerbal
  - inconsistency!

**Comment by linuxgurugamer** [comment]
Please confirm that the referenced commit fixes this

**Comment by cake-pie** [comment]
Yes. By explicitly setting KLevel = 5 when experience system is off i.e. correctly reflects that all new hires are at the max level (5 stars) it now ensures hiring cost will now be consistent. Previously it forgot to set the var at all so whatever value it had (by default or from another game) would have been used.

**Comment by linuxgurugamer** [comment]
ok, thanks, that means I can close t his
